<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVe26p05\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVe26p05/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVe26p05.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerVe26p05\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerVe26p05\appProdProjectContainer(array(
    'container.build_hash' => 'Ve26p05',
    'container.build_id' => '21d7ddc4',
    'container.build_time' => 1547030901,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVe26p05');
