<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'coresphere_console.controller' shared service.

return $this->services['coresphere_console.controller'] = new \CoreSphere\ConsoleBundle\Controller\ConsoleController(${($_ = isset($this->services['templating']) ? $this->services['templating'] : $this->load('getTemplatingService.php')) && false ?: '_'}, ${($_ = isset($this->services['coresphere_console.executer']) ? $this->services['coresphere_console.executer'] : ($this->services['coresphere_console.executer'] = new \CoreSphere\ConsoleBundle\Executer\CommandExecuter(${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel', 1)) && false ?: '_'}))) && false ?: '_'}, ${($_ = isset($this->services['coresphere_console.application']) ? $this->services['coresphere_console.application'] : $this->load('getCoresphereConsole_ApplicationService.php')) && false ?: '_'}, 'dev');
