<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'coresphere_console.routing' shared service.

return $this->services['coresphere_console.routing'] = new \CoreSphere\ConsoleBundle\Routing\Loader(${($_ = isset($this->services['routing.loader.yml']) ? $this->services['routing.loader.yml'] : $this->load('getRouting_Loader_YmlService.php')) && false ?: '_'});
