<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'coresphere_console.application' shared service.

return $this->services['coresphere_console.application'] = ${($_ = isset($this->services['coresphere_console.application.factory']) ? $this->services['coresphere_console.application.factory'] : ($this->services['coresphere_console.application.factory'] = new \CoreSphere\ConsoleBundle\Console\ApplicationFactory())) && false ?: '_'}->create(${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel', 1)) && false ?: '_'});
