<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oc_platform.antispam' shared service.

$this->services['oc_platform.antispam'] = $instance = new \OC\PlatformBundle\Antispam\OCAntispam(${($_ = isset($this->services['swiftmailer.mailer.default']) ? $this->services['swiftmailer.mailer.default'] : $this->load('getSwiftmailer_Mailer_DefaultService.php')) && false ?: '_'}, 'fr', 50);

$instance->setLocale('fr');

return $instance;
