<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'coresphere_console.executer' shared service.

return $this->services['coresphere_console.executer'] = new \CoreSphere\ConsoleBundle\Executer\CommandExecuter(${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel', 1)) && false ?: '_'});
