<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'coresphere_console.application.factory' shared service.

return $this->services['coresphere_console.application.factory'] = new \CoreSphere\ConsoleBundle\Console\ApplicationFactory();
